version: '3.1'

services:
  honeypot:
    build: ./honeypot
    restart: unless-stopped
    container_name: honeypot
    ports:
      - '21:21'
      - '4242:22'
      - '25:25'
    cap_add:
      - NET_ADMIN
    depends_on:
      - postgres
    networks:
      - backend
      - frontend
    expose:
      - '21'
      - '22'
      - '23'
      - '25'
      - '53'
      - '80'
      - '110'
      - '143'
      - '443'
      - '445'
      - '1080'
      - '3306'
      - '3389'
      - '5900'
      - '6379'
      - '8080'

  grafana:
    build: ./grafana
    restart: unless-stopped
    container_name: grafana
    command: ./import.sh
    ports:
      - '8000:3000'
    links:
      - postgres
    depends_on:
      - honeypot
    networks:
      - backend
      - frontend
    environment:
      GF_SECURITY_ADMIN_USER: navneet
      GF_SECURITY_ADMIN_PASSWORD: Navneet123
    logging:
        driver: none

  postgres:
    image: postgres:9.6
    container_name: postgres
    restart: unless-stopped
    networks:
      - backend
    command: -p 9999
    environment:
      POSTGRES_USER: changeme027a088931d22
      POSTGRES_PASSWORD: changeme0f40773877963
    logging:
        driver: none

networks:
  frontend:
    internal: false
  backend:
    internal: true
